# Generated by Django 5.2.1 on 2025-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
