# Generated by Django 5.2.1 on 2025-05-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_customuser_rol_alter_customuser_puntaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messaje',
            new_name='message',
        ),
    ]