# Generated by Django 5.1 on 2025-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0005_event_id_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_img',
            field=models.CharField(default='sin_imagen', max_length=2083),
        ),
    ]
