# Generated by Django 5.2.1 on 2025-06-10 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0006_category_id_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
