# Generated by Django 5.2 on 2025-06-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0008_alter_ticket_event_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
