# Generated by Django 5.1.4 on 2025-06-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0009_ticket_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
