# Generated by Django 5.2 on 2025-06-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0010_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacidad_ocupada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='cantidad_puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='suma_puntaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
