# Generated by Django 5.2.1 on 2025-06-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0011_alter_event_cancelado_alter_event_cantidad_puntos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'permissions': [('can_accept_refund', 'Puede aceptar reembolsos'), ('can_reject_refund', 'Puede rechazar reembolsos')]},
        ),
    ]
