# Generated by Django 5.2 on 2025-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0011_event_capacidad_ocupada_alter_event_cancelado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
    ]
