# Generated by Django 5.2 on 2025-06-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0011_alter_event_cancelado_alter_event_cantidad_puntos_and_more'),
        ('eventos_app', '0012_alter_venue_capacity'),
    ]

    operations = [
    ]
