# Generated by Django 5.1 on 2025-06-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0012_alter_refundrequest_options'),
        ('eventos_app', '0013_merge_20250613_1948'),
    ]

    operations = [
    ]
