# Generated by Django 5.2 on 2025-06-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0014_merge_20250613_2119'),
        ('eventos_app', '0014_merge_20250614_0236'),
    ]

    operations = [
    ]
