# Generated by Django 5.2.1 on 2025-06-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0014_merge_20250613_2032'),
        ('eventos_app', '0015_merge_20250616_0043'),
    ]

    operations = [
    ]
