# Generated by Django 5.2 on 2025-06-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0015_merge_20250616_0043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
