# Generated by Django 5.2 on 2025-06-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0016_alter_comment_unique_together'),
        ('eventos_app', '0016_merge_20250617_1815'),
    ]

    operations = [
    ]
