# Generated by Django 5.2 on 2025-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0017_merge_20250618_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cantidad_puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacidad_ocupada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
