# Generated by Django 5.2 on 2025-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0018_alter_customuser_puntaje_alter_event_cantidad_puntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categoria',
        ),
        migrations.AddField(
            model_name='event',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='events', to='eventos_app.category'),
        ),
    ]
