# Generated by Django 5.2 on 2025-06-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0018_alter_event_cantidad_puntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
