# Generated by Django 5.2 on 2025-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0019_alter_customuser_puntaje_alter_venue_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
