# Generated by Django 5.2 on 2025-06-24 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0019_remove_event_categoria_event_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100, verbose_name='Nombre del titular')),
                ('numero_tarjeta', models.CharField(max_length=16, verbose_name='Número de tarjeta')),
                ('fecha_vencimiento', models.CharField(max_length=5, verbose_name='Fecha de expiración (MM/AA)')),
                ('cvv', models.CharField(max_length=4, verbose_name='Código de seguridad (CVV)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos_app.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
